#Input Variables
input_number:
  command_setpoint:
    name: Boiler set point
    initial: 0
    min: 0
    max: 65
    step: 1
    unit_of_measurement: "°C"
    mode: box
  msgid_17:
    name: Relative modulation level
    min: 0
    max: 100
    step: 1
    unit_of_measurement: "%"
    mode: box
  msgid_25:
    name: Boiler water temperature
    min: 0
    max: 100
    step: 1
    unit_of_measurement: "°C"
    mode: box
  msgid_26:
    name: DHW temperature
    min: 0
    max: 100
    step: 1
    unit_of_measurement: "°C"
    mode: box
  msgid_28:
    name: Return water temperature
    min: 0
    max: 100
    step: 1
    unit_of_measurement: "°C"
    mode: box
  msgid_56:
    name: DHW setpoint
    min: 0
    max: 100
    step: 1
    unit_of_measurement: "°C"
    mode: box
  msgid_57:
    name: Max CH water setpoint
    min: 0
    max: 100
    step: 1
    unit_of_measurement: "°C"
    mode: box
  msgid_116:
    name: Burner starts
    min: 0
    max: 100000
    step: 1
    mode: box
  msgid_117:
    name: CH pump starts
    min: 0
    max: 100000
    step: 1
    mode: box
  msgid_118:
    name: DHW pump/valve starts
    min: 0
    max: 100000
    step: 1
    mode: box
  msgid_119:
    name: DHW burner starts
    min: 0
    max: 10000
    step: 1
    mode: box
  msgid_120:
    name: Burner operation hours
    min: 0
    max: 100000
    step: 1
    unit_of_measurement: "h"
    mode: box
  msgid_121:
    name: CH pump operation hours
    min: 0
    max: 100000
    step: 1
    unit_of_measurement: "h"
    mode: box
  msgid_122:
    name: DHW pump/valve operation hours
    min: 0
    max: 100000
    step: 1
    unit_of_measurement: "h"
    mode: box
  msgid_123:
    name: DHW burner operation hours
    min: 0
    max: 1000000
    step: 1
    unit_of_measurement: "h"
    mode: box

#text variables
input_text:
  msgid_0:
    name: Status
    initial: Waiting for update
